# Welcome to Jekyll!

# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Nei's blog
email: nrauni@gmail.com
author: Nei Rauni Santos
description: > # this means to ignore newlines until "baseurl:"
  Just another personal blog to share useless stuff. 
  Startup, Finance, Geek, Productivety, Life hacks, Development and maybe more.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://nei.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: nrauni
github_username:  nei

# Build settings
repository: nei/nei.github.io
google_analytics: UA-79593243-2
markdown: kramdown
theme: minima
permalink: pretty
disqus:
    shortname: neis-blog
gems:
  - jekyll-feed
  - jekyll-github-metadata
exclude:
  - Gemfile
  - Gemfile.lock
